name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev \
          libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev \
          libjpeg-dev libfreetype6-dev libharfbuzz-dev
          python3 -m pip install --upgrade pip
          python3 -m pip install buildozer cython==0.29.33

      - name: Build with Buildozer
        run: |
          sudo chown -R runner:docker .
          # ตรวจสอบก่อนว่าถ้ามีโฟลเดอร์ .buildozer ถึงจะทำการ clean เพื่อป้องกัน Error
          if [ -d ".buildozer" ]; then buildozer android clean; fi
          yes | buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GoPDF-APK
          path: bin/*.apk
